
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
  
Metrics/LineLength:
  Max: 140

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'lib/ingredients_migrator.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
